import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const noto = Noto_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "300", "500", "700", "900"],
});

export const metadata = {
  title: "Optidan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${noto.variable} antialiased`}>
        <Navbar />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
