"use client";
// import { Noto_Sans } from "next/font/google";
import TopNav from "./components/topnav/TopNav";
import DashboardFooter from "./components/DashboardFooter";
import Sidebar from "./components/Sidebar";
import { useState } from "react";
// import "./globals.css";
// import Footer from "./components/Footer ";
// import TopNav from "./components/topnav/TopNav";
// import Sidebar from "./components/Sidebar";

// const noto = Noto_Sans({
//   subsets: ["latin"],
//   display: "swap",
//   weight: ["100", "300", "500", "700", "900"],
// });

// export const metadata = {
//   title: "Optidan",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({ children }) {
  const [isOpen, setIsOpen] = useState(true);
  const toggleSidebar = () => {
    setIsOpen(!isOpen);
  };
  return (
    <html lang="en">
      {/* <body className={`${noto.variable} antialiased dashboard`}> */}
      <body>
        <div>
          <div>
            <TopNav />
          </div>
          <div className="flex">
            <Sidebar
              isOpen={isOpen}
              setIsOpen={setIsOpen}
              toggleSidebar={toggleSidebar}
            />
            {/* <main>{children}</main> */}
            <main
              className={`bg-gray-50 flex-1 p-6 transition-all duration-300 ${
                isOpen ? "" : "ml-22"
              }`}
            >
              {children}
            </main>
          </div>
        </div>
        <DashboardFooter />
      </body>
    </html>
  );
}
